// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bshkpgvnaoqsaeynqpci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzaGtwZ3ZuYW9xc2FleW5xcGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTg2MDcsImV4cCI6MjA3MDg5NDYwN30.oQ0KacnncdjcCqPG1yuNTKmoC8qagZGuhgM4KezDZzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});